version: '3.8'

services:
  # 数据库服务
  mysql:
    image: mysql:8.0
    container_name: ryan-mall-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ryan_mall
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ryan-mall-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: ryan-mall-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ryan-mall-network

  # Kafka消息队列
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ryan-mall-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ryan-mall-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ryan-mall-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ryan-mall-network

  # Consul服务发现
  consul:
    image: consul:latest
    container_name: ryan-mall-consul
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    networks:
      - ryan-mall-network

  # Jaeger链路追踪
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ryan-mall-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - ryan-mall-network

  # Prometheus监控
  prometheus:
    image: prom/prometheus:latest
    container_name: ryan-mall-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ryan-mall-network

  # Grafana可视化
  grafana:
    image: grafana/grafana:latest
    container_name: ryan-mall-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ryan-mall-network

volumes:
  mysql_data:
  redis_data:
  grafana_data:

networks:
  ryan-mall-network:
    driver: bridge
