# Redis集群部署配置
# 3主3从高可用Redis集群

version: '3.8'

services:
  # Redis集群节点1 (主节点)
  redis-node-1:
    image: redis:7-alpine
    container_name: ryan-mall-redis-node-1
    restart: always
    ports:
      - "7001:6379"
      - "17001:16379"
    volumes:
      - ./docker/redis-cluster/node-1:/data
      - ./docker/redis-cluster/redis-node-1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      ryan-mall-cluster:
        ipv4_address: 172.20.0.11

  # Redis集群节点2 (主节点)
  redis-node-2:
    image: redis:7-alpine
    container_name: ryan-mall-redis-node-2
    restart: always
    ports:
      - "7002:6379"
      - "17002:16379"
    volumes:
      - ./docker/redis-cluster/node-2:/data
      - ./docker/redis-cluster/redis-node-2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      ryan-mall-cluster:
        ipv4_address: 172.20.0.12

  # Redis集群节点3 (主节点)
  redis-node-3:
    image: redis:7-alpine
    container_name: ryan-mall-redis-node-3
    restart: always
    ports:
      - "7003:6379"
      - "17003:16379"
    volumes:
      - ./docker/redis-cluster/node-3:/data
      - ./docker/redis-cluster/redis-node-3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      ryan-mall-cluster:
        ipv4_address: 172.20.0.13

  # Redis集群节点4 (从节点)
  redis-node-4:
    image: redis:7-alpine
    container_name: ryan-mall-redis-node-4
    restart: always
    ports:
      - "7004:6379"
      - "17004:16379"
    volumes:
      - ./docker/redis-cluster/node-4:/data
      - ./docker/redis-cluster/redis-node-4.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      ryan-mall-cluster:
        ipv4_address: 172.20.0.14

  # Redis集群节点5 (从节点)
  redis-node-5:
    image: redis:7-alpine
    container_name: ryan-mall-redis-node-5
    restart: always
    ports:
      - "7005:6379"
      - "17005:16379"
    volumes:
      - ./docker/redis-cluster/node-5:/data
      - ./docker/redis-cluster/redis-node-5.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      ryan-mall-cluster:
        ipv4_address: 172.20.0.15

  # Redis集群节点6 (从节点)
  redis-node-6:
    image: redis:7-alpine
    container_name: ryan-mall-redis-node-6
    restart: always
    ports:
      - "7006:6379"
      - "17006:16379"
    volumes:
      - ./docker/redis-cluster/node-6:/data
      - ./docker/redis-cluster/redis-node-6.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      ryan-mall-cluster:
        ipv4_address: 172.20.0.16

  # Redis集群管理工具
  redis-cluster-manager:
    image: redis:7-alpine
    container_name: ryan-mall-redis-cluster-manager
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    volumes:
      - ./docker/redis-cluster/cluster-init.sh:/cluster-init.sh
    command: sh /cluster-init.sh
    networks:
      - ryan-mall-cluster

  # Redis Insight - Redis可视化管理工具
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: ryan-mall-redis-insight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    networks:
      - ryan-mall-cluster

  # MySQL数据库 (保持原有配置)
  mysql:
    image: mysql:8.0
    container_name: ryan-mall-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ryan_mall
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - ryan-mall-cluster

# 数据卷定义
volumes:
  mysql_data:
    driver: local
  redis_insight_data:
    driver: local

# 网络定义
networks:
  ryan-mall-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
