groups:
  # 应用程序告警规则
  - name: ryan-mall-app
    rules:
      # 应用程序宕机
      - alert: RyanMallAppDown
        expr: up{job="ryan-mall-app"} == 0
        for: 30s
        labels:
          severity: critical
          service: ryan-mall
        annotations:
          summary: "Ryan Mall应用程序宕机"
          description: "Ryan Mall应用程序已宕机超过30秒"

      # HTTP请求错误率过高
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: ryan-mall
        annotations:
          summary: "HTTP错误率过高"
          description: "HTTP 5xx错误率超过10%，当前值: {{ $value | humanizePercentage }}"

      # 响应时间过长
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: ryan-mall
        annotations:
          summary: "响应时间过长"
          description: "95%的请求响应时间超过1秒，当前值: {{ $value }}s"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 1024
        for: 5m
        labels:
          severity: warning
          service: ryan-mall
        annotations:
          summary: "内存使用率过高"
          description: "应用程序内存使用超过1GB，当前值: {{ $value }}MB"

  # Redis集群告警规则
  - name: redis-cluster
    rules:
      # Redis节点宕机
      - alert: RedisNodeDown
        expr: up{job="redis-cluster"} == 0
        for: 30s
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis节点宕机"
          description: "Redis节点 {{ $labels.instance }} 已宕机"

      # Redis内存使用率过高
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis内存使用率过高"
          description: "Redis内存使用率超过80%，当前值: {{ $value | humanizePercentage }}"

      # Redis连接数过多
      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis连接数过多"
          description: "Redis连接数超过100，当前值: {{ $value }}"

      # Redis集群状态异常
      - alert: RedisClusterStateError
        expr: redis_cluster_state != 1
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis集群状态异常"
          description: "Redis集群状态不正常"

  # MySQL数据库告警规则
  - name: mysql
    rules:
      # MySQL宕机
      - alert: MySQLDown
        expr: up{job="mysql"} == 0
        for: 30s
        labels:
          severity: critical
          service: mysql
        annotations:
          summary: "MySQL数据库宕机"
          description: "MySQL数据库已宕机"

      # MySQL连接数过多
      - alert: MySQLHighConnections
        expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          service: mysql
        annotations:
          summary: "MySQL连接数过多"
          description: "MySQL连接数使用率超过80%，当前值: {{ $value | humanizePercentage }}"

      # MySQL慢查询过多
      - alert: MySQLHighSlowQueries
        expr: rate(mysql_global_status_slow_queries[5m]) > 1
        for: 5m
        labels:
          severity: warning
          service: mysql
        annotations:
          summary: "MySQL慢查询过多"
          description: "MySQL慢查询频率超过1次/秒，当前值: {{ $value }}"

      # MySQL复制延迟
      - alert: MySQLReplicationLag
        expr: mysql_slave_lag_seconds > 30
        for: 2m
        labels:
          severity: warning
          service: mysql
        annotations:
          summary: "MySQL复制延迟"
          description: "MySQL复制延迟超过30秒，当前值: {{ $value }}s"

  # 系统资源告警规则
  - name: system
    rules:
      # CPU使用率过高
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "CPU使用率过高"
          description: "CPU使用率超过80%，当前值: {{ $value }}%"

      # 内存使用率过高
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "内存使用率过高"
          description: "内存使用率超过85%，当前值: {{ $value }}%"

      # 磁盘使用率过高
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "磁盘使用率过高"
          description: "磁盘使用率超过85%，当前值: {{ $value }}%"

      # 磁盘IO过高
      - alert: HighDiskIO
        expr: rate(node_disk_io_time_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "磁盘IO过高"
          description: "磁盘IO使用率过高，当前值: {{ $value }}"

  # 容器告警规则
  - name: containers
    rules:
      # 容器重启过频繁
      - alert: ContainerHighRestartRate
        expr: rate(container_start_time_seconds[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "容器重启过频繁"
          description: "容器 {{ $labels.name }} 重启过于频繁"

      # 容器内存使用率过高
      - alert: ContainerHighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "容器内存使用率过高"
          description: "容器 {{ $labels.name }} 内存使用率超过80%"

      # 容器CPU使用率过高
      - alert: ContainerHighCPUUsage
        expr: (rate(container_cpu_usage_seconds_total[5m]) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "容器CPU使用率过高"
          description: "容器 {{ $labels.name }} CPU使用率超过80%"
