# Grafana 数据源配置
apiVersion: 1

# 数据源列表
datasources:
  # Prometheus 数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      timeInterval: '15s'
    secureJsonData: {}

  # AlertManager 数据源
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    secureJsonData: {}

  # MySQL 数据源（可选）
  - name: MySQL
    type: mysql
    access: proxy
    url: ryan-mall-mysql:3306
    database: ryan_mall
    user: root
    editable: true
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timezone: 'Asia/Shanghai'
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true
    secureJsonData:
      password: '123456'

  # Redis 数据源（可选）
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://ryan-mall-redis-node-1:6379
    editable: true
    jsonData:
      client: 'cluster'
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: ''

  # Loki 日志数据源（可选）
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   url: http://loki:3100
  #   editable: true
  #   jsonData:
  #     maxLines: 1000
  #     timeout: 60
  #     httpHeaderName1: 'X-Scope-OrgID'
  #   secureJsonData:
  #     httpHeaderValue1: 'tenant1'

  # Jaeger 链路追踪数据源（可选）
  # - name: Jaeger
  #   type: jaeger
  #   access: proxy
  #   url: http://jaeger:16686
  #   editable: true
  #   jsonData:
  #     tracesToLogs:
  #       datasourceUid: 'loki'
  #       tags: ['job', 'instance', 'pod', 'namespace']
  #       mappedTags: [{ key: 'service.name', value: 'service' }]
  #       mapTagNamesEnabled: false
  #       spanStartTimeShift: '1h'
  #       spanEndTimeShift: '1h'
  #       filterByTraceID: false
  #       filterBySpanID: false
  #     tracesToMetrics:
  #       datasourceUid: 'prometheus'
  #       tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
  #       queries:
  #         - name: 'Sample query'
  #           query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
  #     nodeGraph:
  #       enabled: true
  #     search:
  #       hide: false
  #     spanBar:
  #       type: 'Tag'
  #       tag: 'http.path'
